@echo off

mkdir %USERPROFILE%\asir %USERPROFILE%\daw %USERPROFILE%\dam %USERPROFILE%\ceti %USERPROFILE%\ASMR
mkdir %USERPROFILE%\asir\doct%USERPROFILE%\dam\docs %USERPROFILE%\DAM\doc %USERPROFILE%\ceti\doct %USERPROFILE%\ASMR\doct
mkdir %USERPROFILE%\asir\pract %USERPROFILE%\dam\par %USERPROFILE%\DAM\HA %USERPROFILE%\ceti\prar %USERPROFILE%\ASMR\pra
mkdir %USERPROFILE%\asir\exam %USERPROFILE%\dam\exdam %USERPROFILE%\DAM\hue %USERPROFILE%\ceti\enam %USERPROFILE%\ASMR\exen
